#!/usr/bin/env python3
"""Emit the LaTeX contents table for the v2 corpus, straight from the files.

Typing 31 rows of numbers by hand into a report is how reports end up
disagreeing with the data they describe. This reads rows, size, bus and branch
counts, voltage levels and yield off the parquet files and the pandapower
networks, and prints the tabular body ready to paste.
"""
import glob
import io
import os
import re

import numpy as np
import pyarrow.parquet as pq

OUT = "/home/vault/iwi5/iwi5295h/PIGNN-Attn-LS/ScenarioSynthesis_PPC/out"
TAG = "u0clean_sgenpert_pvqvstart"
LOGS = "/home/hpc/iwi5/iwi5295h/PIGNN-Attn-LS/ScenarioSynthesis_PPC/sbatch/Job_out"

CGMES = {"SimBench", "ENTSO_E_RealGridTest", "LVN_heo1"}

# Display name -> pandapower network attribute (for kV levels / branch count)
TEXNAME = {
    "case24_ieee_rts": r"case24\_ieee\_rts", "case_ieee30": r"case\_ieee30",
    "case_illinois200": r"case\_illinois200", "LVN_heo1": r"LVN\_heo1",
    "ENTSO_E_RealGridTest": r"ENTSO\_E\_RealGridTest",
}


def L(b):
    return np.load(io.BytesIO(b), allow_pickle=False)


SBATCH = "/home/hpc/iwi5/iwi5295h/PIGNN-Attn-LS/ScenarioSynthesis_PPC/sbatch"


def attempts_for(grid):
    """--runs for this grid, i.e. attempts.

    Read from the sbatch script rather than the log: the log only states the
    attempt count when a rename happened, which is exactly the grids that did
    NOT reach 100% yield. Taking it from the log alone left every full-yield
    grid blank and made the corpus total meaningless.
    """
    p = os.path.join(SBATCH, f"{grid}_ppnr_v2.sh")
    if os.path.exists(p):
        m = re.search(r"--runs\s+(\d+)", open(p, errors="ignore").read())
        if m:
            return int(m.group(1))
    p = os.path.join(LOGS, f"{grid}_ppnr_v2.out")
    if os.path.exists(p):
        m = re.search(r"renamed to true row count: (\d+) attempted",
                      open(p, errors="ignore").read())
        if m:
            return int(m.group(1))
    return None


def main():
    rows = []
    for f in sorted(glob.glob(f"{OUT}/*{TAG}*directSI.parquet")):
        grid = os.path.basename(f).split("_ppcY_")[0]
        pf = pq.ParquetFile(f)
        n = pf.metadata.num_rows
        gb = os.path.getsize(f) / 1e6           # MB, matching the old report
        t = pf.read_row_group(0)
        bt = L(t["bus_typ"][0].as_py())
        nb = len(bt)
        nbr = int(t["branch_number"][0].as_py())
        vn = L(t["vn_kv"][0].as_py())
        lv = len(np.unique(np.round(vn, 6)))
        lo, hi = float(vn.min()), float(vn.max())
        att = attempts_for(grid)
        yld = (n / att) if att else float("nan")
        rows.append(dict(grid=grid, n=n, mb=gb, nb=nb, nbr=nbr, lv=lv,
                         lo=lo, hi=hi, att=att, yld=yld,
                         src="CGMES" if grid in CGMES else "PPC"))

    rows.sort(key=lambda r: r["nb"])
    def num(x, dec=0):
        """LaTeX thousands separator, applied exactly once."""
        return f"{x:,.{dec}f}".replace(",", "{,}")

    missing = [r["grid"] for r in rows if not r["att"]]
    if missing:
        print(f"% WARNING: no attempt count for {missing} -- totals would be wrong")

    print("% --- generated by collect_v2_table.py, do not hand-edit ---")
    for r in rows:
        name = TEXNAME.get(r["grid"], r["grid"])
        kv = f"{r['lo']:g}" if abs(r["hi"] - r["lo"]) < 1e-9 else f"{r['lo']:g}--{r['hi']:g}"
        y = "---" if np.isnan(r["yld"]) else f"{r['yld'] * 100:.1f}" + r"\%"
        att = "---" if not r["att"] else num(r["att"])
        print(f"{name:<26} & {num(r['nb'])} & {num(r['nbr'])} & {num(r['n'])} & {att} "
              f"& {y} & {num(r['mb'], 1)} & {r['lv']} & {kv} & {r['src']} \\\\")

    tot_rows = sum(r["n"] for r in rows)
    tot_mb = sum(r["mb"] for r in rows)
    tot_att = sum(r["att"] for r in rows) if not missing else None
    ty = "---" if tot_att is None else f"{tot_rows / tot_att * 100:.1f}" + r"\%"
    ta = "---" if tot_att is None else num(tot_att)
    print(r"\midrule")
    print(f"\\textbf{{Total ({len(rows)})}} & & & \\textbf{{{num(tot_rows)}}} & "
          f"\\textbf{{{ta}}} & \\textbf{{{ty}}} & \\textbf{{{num(tot_mb, 1)}}} & & & \\\\")
    ov = "n/a" if tot_att is None else f"{tot_rows / tot_att:.1%}"
    print(f"\n% files={len(rows)}  rows={tot_rows:,}  attempts={tot_att}  "
          f"GB={tot_mb / 1000:.1f}  overall yield={ov}")


if __name__ == "__main__":
    main()
